---
- include: ../vars/varsDebian.yml

- name: Install tzdata and ntp
  apt:
    update_cache: true
    name: "{{ packages }}"
    state: present

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Configure NTP
  template:
    src: ntp.conf.j2
    dst: /etc/ntp.conf
  notify: ntp_restart
  when: ntp_manage_config

- name: Start NTP deamon
  service:
    name: ntp
    state: started
    enabled: true
  when: ntp_enabled
